import os
import sys
import queue
import threading
import subprocess
import tempfile
import shutil
import time
import uuid
import requests
from flask import Flask, request, jsonify, Response, send_from_directory

app = Flask(__name__, static_folder="../frontend", static_url_path="/")

# Global state for the single local user session
class BotSession:
    def __init__(self):
        self.log_queue = queue.Queue()
        self.confirm_queue = queue.Queue()
        self.is_running = False
        self.worker_thread = None

session = BotSession()

def broadcast(msg_type, content, action=None):
    msg = {"type": msg_type, "content": content}
    if action:
        msg["action"] = action
    session.log_queue.put(msg)

def run_git_operations(repo_url, pat, owner, repo):
    temp_dir = tempfile.mkdtemp(prefix="badge_bot_")
    branch_name = f"badge-bot-{uuid.uuid4().hex[:8]}"
    
    try:
        # Prepare auth URL
        if repo_url.startswith("https://"):
            auth_url = repo_url.replace("https://", f"https://x-access-token:{pat}@")
        else:
            broadcast("error", "Invalid repo URL format. Must start with https://")
            return

        broadcast("log", f"Cloning repository {owner}/{repo} into temporary directory...")
        
        # Clone
        subprocess.run(["git", "clone", auth_url, temp_dir], check=True, capture_output=True, text=True)
        broadcast("log", "Clone successful.")
        
        # Checkout new branch
        subprocess.run(["git", "checkout", "-b", branch_name], cwd=temp_dir, check=True, capture_output=True, text=True)
        broadcast("log", f"Created and checked out new branch: {branch_name}")

        # Make a dummy change
        dummy_file = os.path.join(temp_dir, "PING.txt")
        with open(dummy_file, "a") as f:
            f.write(f"Ping from Badge Bot at {time.time()}\n")
        
        broadcast("log", f"Created a dummy change in PING.txt")

        # Confirm Stage
        broadcast("confirm", "Ready to stage changes (git add). Proceed?", "stage")
        if session.confirm_queue.get() != "yes":
            broadcast("log", "Operation aborted by user.")
            return

        broadcast("log", "Staging changes...")
        subprocess.run(["git", "add", "PING.txt"], cwd=temp_dir, check=True, capture_output=True, text=True)
        broadcast("log", "Changes staged successfully.")

        # Confirm Commit
        broadcast("confirm", "Ready to commit changes (git commit). Proceed?", "commit")
        if session.confirm_queue.get() != "yes":
            broadcast("log", "Operation aborted by user.")
            return

        broadcast("log", "Committing changes...")
        # configure git user if not set locally
        subprocess.run(["git", "config", "user.name", "Badge Bot"], cwd=temp_dir, check=False)
        subprocess.run(["git", "config", "user.email", "badgebot@example.com"], cwd=temp_dir, check=False)
        
        subprocess.run(["git", "commit", "-m", "Unlock badge: PING from bot"], cwd=temp_dir, check=True, capture_output=True, text=True)
        broadcast("log", "Commit successful.")

        # Confirm Push
        broadcast("confirm", f"Ready to push branch {branch_name} to origin. Proceed?", "push")
        if session.confirm_queue.get() != "yes":
            broadcast("log", "Operation aborted by user.")
            return

        broadcast("log", "Pushing to remote...")
        subprocess.run(["git", "push", "-u", "origin", branch_name], cwd=temp_dir, check=True, capture_output=True, text=True)
        broadcast("log", "Push successful.")

        # Confirm PR
        broadcast("confirm", "Ready to open a Pull Request. Proceed?", "pr")
        if session.confirm_queue.get() != "yes":
            broadcast("log", "Operation aborted by user.")
            return

        broadcast("log", "Opening Pull Request via GitHub API...")
        pr_url = f"https://api.github.com/repos/{owner}/{repo}/pulls"
        headers = {
            "Authorization": f"Bearer {pat}",
            "Accept": "application/vnd.github.v3+json"
        }
        data = {
            "title": "Badge Bot: Dummy PR to unlock badges",
            "head": branch_name,
            "base": "main", # Note: assuming main branch, could be master
            "body": "This is an automated PR generated by Badge Bot to unlock badges."
        }
        resp = requests.post(pr_url, headers=headers, json=data)
        
        if resp.status_code == 201:
            pr_data = resp.json()
            broadcast("log", f"Pull Request opened successfully: {pr_data.get('html_url')}")
            broadcast("done", "All operations completed successfully! Check the chatbot for newly unlocked badges.")
        else:
            # Maybe base is master?
            if "master" in resp.text:
                data["base"] = "master"
                resp = requests.post(pr_url, headers=headers, json=data)
                if resp.status_code == 201:
                    pr_data = resp.json()
                    broadcast("log", f"Pull Request opened successfully: {pr_data.get('html_url')}")
                    broadcast("done", "All operations completed successfully! Check the chatbot for newly unlocked badges.")
                    return
            broadcast("error", f"Failed to open PR: {resp.status_code} - {resp.text}")

    except subprocess.CalledProcessError as e:
        broadcast("error", f"Git command failed: {e.cmd}\nOutput: {e.output}\nError: {e.stderr}")
    except Exception as e:
        broadcast("error", f"An unexpected error occurred: {str(e)}")
    finally:
        session.is_running = False
        try:
            # Windows might have issues removing git dirs, so ignore errors
            shutil.rmtree(temp_dir, ignore_errors=True)
        except:
            pass

@app.route('/')
def index():
    return send_from_directory('../frontend', 'index.html')

@app.route('/<path:path>')
def static_files(path):
    return send_from_directory('../frontend', path)

@app.route('/api/start', methods=['POST'])
def start_bot():
    if session.is_running:
        return jsonify({"error": "A session is already running."}), 400

    data = request.json
    repo_url = data.get("repo_url", "").strip()
    pat = data.get("pat", "").strip()

    if not repo_url or not pat:
        return jsonify({"error": "Repo URL and PAT are required."}), 400

    # Parse owner and repo from URL
    # Handle both https://github.com/owner/repo.git and https://github.com/owner/repo
    url_parts = repo_url.rstrip("/").split("/")
    if len(url_parts) < 2:
        return jsonify({"error": "Invalid repo URL."}), 400
    
    repo = url_parts[-1]
    if repo.endswith(".git"):
        repo = repo[:-4]
    owner = url_parts[-2]

    # Validate with API
    headers = {"Authorization": f"Bearer {pat}", "Accept": "application/vnd.github.v3+json"}
    resp = requests.get(f"https://api.github.com/repos/{owner}/{repo}", headers=headers)
    if resp.status_code != 200:
        return jsonify({"error": f"Failed to access repository. Check URL and PAT. (HTTP {resp.status_code})"}), 400

    # Clear queues
    while not session.log_queue.empty():
        session.log_queue.get_nowait()
    while not session.confirm_queue.empty():
        session.confirm_queue.get_nowait()

    session.is_running = True

    session.worker_thread = threading.Thread(
        target=run_git_operations,
        args=(repo_url, pat, owner, repo)
    )
    session.worker_thread.start()

    return jsonify({"owner": owner, "repo": repo, "branch": resp.json().get("default_branch", "main")})

@app.route('/api/confirm', methods=['POST'])
def confirm_action():
    data = request.json
    answer = data.get("answer") # "yes" or "no"
    if answer not in ["yes", "no"]:
        return jsonify({"error": "Invalid answer."}), 400
    session.confirm_queue.put(answer)
    return jsonify({"status": "ok"})

@app.route('/api/stream')
def stream():
    def event_stream():
        import json
        while True:
            try:
                # Use a timeout to occasionally send keepalives or check if disconnected
                msg = session.log_queue.get(timeout=1.0)
                yield f"data: {json.dumps(msg)}\n\n"
            except queue.Empty:
                yield ": keepalive\n\n"
    return Response(event_stream(), mimetype="text/event-stream")

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=5000, debug=True, threaded=True)
